apiVersion: v1
kind: Pod
metadata:
  name: wlipoc-pod
  namespace: wlipoc
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: workload-identity-sa
  containers:
  - name: alpine-container
    image: alpine
    command: ["/bin/sh", "-c", "--"]
    args: ["while true; do sleep 30; done;"]
